services:
  autocatalogdb:
    image: postgres
    
  adservicedb:
    image: postgres
    
  autocatalog.web:
    image: autocatalog.web
    build:
      context: .
      dockerfile: src/Services/AutoCatalog/AutoCatalog.Web/Dockerfile
      
  keycloak:
    image: quay.io/keycloak/keycloak
    
  keycloakdb:
    image: postgres
    
  minio:
    image: minio/minio:latest
    
  filemanagement.grpc:
    image: filemanagement.grpc
    build:
      context: .
      dockerfile: src/Services/FileManagement/FileManagement.Grpc/Dockerfile
      
  profileservice.web:
    image: profileservice.web
    build:
      context: .
      dockerfile: src/Services/ProfileService/ProfileService.Web/Dockerfile
      
      
volumes:
  auto-catalog-postgres:
  ad-service-postgres:
  keycloak-data:
  minio-data:
    driver: local
  
  
  

