services:
  autocatalogdb:
    image: postgres
    
  adservicedb:
    image: postgres
    
  autocatalog.web:
    image: autocatalog.web
    build:
      context: .
      dockerfile: src/Services/AutoCatalog/AutoCatalog.Web/Dockerfile
      
  keycloak:
    image: quay.io/keycloak/keycloak
    
  keycloakdb:
    image: postgres
    
  minio:
    image: minio/minio:latest
    
  

    
volumes:
  auto-catalog-postgres:
  ad-service-postgres:
  keycloak-data:
  minio-data:
    driver: local
  
  