services:
  autocatalogdb:
    image: postgres
    
  adservicedb:
    image: postgres
    
  redis:
    image: redis:latest
    
  autocatalog.web:
    image: autocatalog.web
    build:
      context: .
      dockerfile: src/Services/AutoCatalog/AutoCatalog.Web/Dockerfile
      
  keycloak:
    image: quay.io/keycloak/keycloak
    
  keycloakdb:
    image: postgres
    
  minio:
    image: minio/minio:latest
    
  filemanagement.grpc:
    image: filemanagement.grpc
    build:
      context: .
      dockerfile: src/Services/FileManagement/FileManagement.Grpc/Dockerfile
      
  profileservicedb:
    image: postgres

      
      
volumes:
  auto-catalog-postgres:
  ad-service-postgres:
  profile-service-postgres-data:
  keycloak-data:
  minio-data:
    driver: local
  redis-data:
    driver: local
  
  
  

